// Tiny original pixel sprites. No downloaded art or runtime asset requests.
const palette = {
  o: "#213b2d",
  w: "#eee6c9",
  g: "#98b77d",
  G: "#c6d3a0",
  y: "#d8b86c",
  b: "#82adba",
  B: "#527f94",
  r: "#b96655",
  R: "#e9a38a",
  s: "#e4b791",
  h: "#624c35",
  H: "#98734c",
  d: "#405b3c",
};
const sprites = {
  leaf: [
    "................",
    "........gggggg..",
    "......ggGGGGgg..",
    "....ggGGGGGGgg..",
    "....ggGGGGgggg..",
    "..ggGGGGgggg....",
    "..ggGGgggg......",
    "..gggggg........",
    "....gg..........",
    "..gg............",
    "..gg............",
    "................",
  ],
  sword: [
    "...........ww...",
    "..........wGw...",
    ".........wGw....",
    "........wGw.....",
    ".......wGw......",
    "......wGw.......",
    ".....wGw........",
    "..y.wGw.........",
    "...yyw..........",
    "....yy..........",
    "...H.yy.........",
    "..HH..y.........",
    ".HH.............",
    "................",
  ],
  potion: [
    "......HHHH......",
    ".....yyyyyy.....",
    "......wwww......",
    "......wwww......",
    "....wwRRRRww....",
    "...wwrRRRRRww...",
    "...wrrRRRRRRw...",
    "...wrrRRRwwRw...",
    "...wrrRRRwwRw...",
    "...wrrrrRRRRw...",
    "....wrrrrRRw....",
    ".....wwwwww.....",
    "................",
    "................",
  ],
  bag: [
    ".....yyyyyy.....",
    "....yy....yy....",
    "....yy....yy....",
    "...HHHHHHHHHH...",
    "..HHHHHHHHHHHH..",
    "..HHHyyyyyyHHH..",
    "..HHHyyyyyyHHH..",
    "..HHHyyyyyyHHH..",
    "..HHHHHyyHHHHH..",
    "..HHHHHyyHHHHH..",
    "..HHHHHHHHHHHH..",
    "...HHHHHHHHHH...",
    "................",
    "................",
  ],
  portrait: [
    "....hhhhhhhh....",
    "...hhhHHHHhhh...",
    "...hHHHHHHHHh...",
    "...hssssssssH...",
    "...ssossossso...",
    "....ssssssss....",
    ".....ssRRss.....",
    "....ggGGgggg....",
    "...gggGGggggg...",
    "..ggggGGgggggg..",
    "..ssggyyggggss..",
    "...gggyygggg....",
    "...HHH..HHHH....",
    "...ooo..oooo....",
  ],
  mira: [
    ".....wwwww......",
    "...wwwwwwwww....",
    "...wwwwwwwww....",
    "...wsssssssw....",
    "...ssossossso...",
    "....sssssss.....",
    ".....ssRss......",
    "....bbBBbbb.....",
    "...bbbBBbbbb....",
    "..bbbbBBbbbbb...",
    "..ssbbyybbbss...",
    "...bbbyybbbb....",
    "...bbbyybbbb....",
    "...ooo..oooo....",
  ],
  coin: [
    "......yyyy......",
    "....yyGGGGyy....",
    "...yyGGyyGGyy...",
    "...yGGGyyGGGy...",
    "..yGGGGyyGGGGy..",
    "..yGGGGyyGGGGy..",
    "..yGGGGyyGGGGy..",
    "..yGGGGyyGGGGy..",
    "...yGGGyyGGGy...",
    "...yyGGGGGGyy...",
    "....yyyyyyyy....",
    "......yyyy......",
    "................",
    "................",
  ],
  crystal: [
    ".......bb.......",
    "......bwwb......",
    ".....bwwwwb.....",
    "....bwwbbwwb....",
    "...bwwbbbbwwb...",
    "...bwbbbbbbwb...",
    "...bbbbbbbbbb...",
    "....bbbbbbbb....",
    ".....bbbbbb.....",
    "......bbbb......",
    ".......bb.......",
    "................",
    "................",
    "................",
  ],
  scroll: [
    "..yyyyyyyyyyy...",
    ".ywwwwwwwwwwyy..",
    ".ywwwwwwwwww.y..",
    "..ywwwwwywwy....",
    "..ywwyyyywwy....",
    "..ywwwwwywwy....",
    "..ywwyyyywwy....",
    "..ywwwwwwwwy....",
    "..ywwyyyywwy....",
    "..ywwwwwwwwy....",
    "..yyyyyyyyyy....",
    ".yywwwwwwyy.....",
    "..yyyyyyyy......",
    "................",
  ],
  dash: [
    "............gg..",
    "..........gggg..",
    ".....gg..ggggg..",
    "....gggggggggg..",
    "...gggggggggg...",
    "..gggggggggg....",
    "....ggggggg.....",
    "...ggggggg......",
    "..gg..ggg.......",
    ".gg....gg.......",
    "........gg......",
    ".........gg.....",
    "................",
    "................",
  ],
  sun: [
    ".......yy.......",
    "..y....yy....y..",
    "...y........y...",
    ".....yyyyyy.....",
    "....yyyyyyyy....",
    "...yyyyyyyyyy...",
    "yy.yyyyyyyyyy.yy",
    "yy.yyyyyyyyyy.yy",
    "...yyyyyyyyyy...",
    "....yyyyyyyy....",
    ".....yyyyyy.....",
    "...y........y...",
    "..y....yy....y..",
    ".......yy.......",
  ],
};
const paths = {
  help: "M7 1h3v2H7zM4 3h3v2H4zM10 3h3v2h-3zM10 5h3v3h-3zM7 8h3v3H7zM7 13h3v2H7z",
  settings:
    "M6 1h4v3H6zM6 12h4v3H6zM1 6h3v4H1zM12 6h3v4h-3zM3 3h3v3H3zM10 3h3v3h-3zM3 10h3v3H3zM10 10h3v3h-3zM4 5h2v6H4zM10 5h2v6h-2zM6 4h4v2H6zM6 10h4v2H6z",
  sound:
    "M1 6h3v4H1zM4 4h2v8H4zM6 2h2v12H6zM10 5h2v6h-2zM12 3h2v2h-2zM14 5h2v6h-2zM12 11h2v2h-2z",
  mute: "M1 6h3v4H1zM4 4h2v8H4zM6 2h2v12H6zM10 5h2v2h-2zM12 7h2v2h-2zM14 9h2v2h-2zM14 5h2v2h-2zM10 9h2v2h-2z",
};
export function icon(name) {
  if (paths[name])
    return `<svg viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="${paths[name]}"/></svg>`;
  const rows = sprites[name] ?? sprites.leaf;
  return `<svg viewBox="0 0 16 14" aria-hidden="true">${rows.map((r, y) => [...r].map((c, x) => (c === "." ? "" : `<rect x="${x}" y="${y}" width="1" height="1" fill="${palette[c]}"/>`)).join("")).join("")}</svg>`;
}
export function paintIcons(root = document) {
  root
    .querySelectorAll("[data-icon]")
    .forEach((el) => (el.innerHTML = icon(el.dataset.icon)));
}
